//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_videoAdapters
    {
        public int id { get; set; }
        public string form_factor { get; set; }
        public int video_memory { get; set; }
        public string title { get; set; }
    }
}
